### ISSUE TITLE
Does aws-http make use of the aws sdk for obtaining keys or otherwise support running in ECS tasks?

### ISSUE THREAD

**Issue by iursinoliveperson** [onicagroup/sailplane#32]
If so, can we add this to the README.md as a feature please? 

Thanks.

**Comment by kernwig** [comment]
It does use AWS-SDK for the credentials. See: https://github.com/onicagroup/sailplane/blob/999da5d9164aaa7cfb1c1b6029e38e1a6390f837/aws-https/lib/aws-https.ts#L163

As such, even though the sailplane collection is targeted at AWS Lambda, it should work within _any_ AWS container.

**Comment by iursinoliveperson** [comment]
Confirmed.
