### ISSUE TITLE
Failure to authenticate with Fargate Task Role after about 8 hours

### ISSUE THREAD

**Issue by iursinoliveperson** [onicagroup/sailplane#33]
Basically after about 8 hours of uptime my fargate ECS tasks are not able to use aws-https to auth to api gateway even though they are still able to auth to other services like secrets manager.

I see a warning log message:
`2020-03-20T13:28:32 WARN aws-https: Failed to load content, status code: 403 "{\"message\":\"The security token included in the request is expired\"}\n"`

And then here is the stack trace:

```
Error: Failed to load content, status code: 403
at IncomingMessage.<anonymous> (/app/node_modules/@sailplane/aws-https/dist/aws-https.js:54:41)
at IncomingMessage.emit (events.js:333:22)
at IncomingMessage.EventEmitter.emit (domain.js:482:12)
at endReadableNT (_stream_readable.js:1204:12)
at processTicksAndRejections (internal/process/task_queues.js:84:21) {
statusCode: 403,
status: 403
}
```

My role for this fargate task has access to Secrets Manager and Lambda as well and I have not observed any problem with those. Secrets manager is definitely still working.

I'm using aws-https to call api gateway with this input:

```
{
hostname: 'redacted.execute-api.us-east-2.amazonaws.com',
path: '/EB1/sites/create',
method: 'POST',
headers: {
Accept: 'application/json',
'X-API-Key': 'redacted',
'Content-Type': 'application/json'
},
body: '{"region":"z2","email":"fake@test.com","firstName":"dwadaw","lastName":"dawdawdaw","password":"redacted"}',
awsSign: true
}
```

my code looks like this:
```
export async function callApiHandleExceptions(request: AwsHttpsOptions) {
    try {
        console.log(request)
        return await new AwsHttps().request(request)
    } catch (err) {
        console.error(err)
        if (err.statusCode) {
            if (err.statusCode === 504) {
                throw errorResponsetoError(DEPENDENCY_GATEWAY_TIMEOUT)
            }
            if (err.statusCode >= 400 && err.statusCode < 500) {
                throw errorResponsetoError(INVALID_REQUEST_MADE)
            }
            throw errorResponsetoError(FAILURE_OF_DEPENDENCY)
        }
        throw Error("Unknown error thrown during aws-http execution.")
    }
}

```

**Comment by kernwig** [comment]
AwsHttps was designed for Lambda, which has shorter life cycles than this. It caches the credentials and reuses it indefinitely. This of course doesn't work for such a long-lived process.

You should be able to work around the problem by periodically clearing the cache by: `AwsHttps['credentialsPromise'] = undefined;` 

You could use [ExpiringValue](https://docs.onica.com/projects/sailplane/en/latest/expiring_value.html) to manage running this code, like:

```
const MillisecondsInHour = 3600000;
https = new ExpiringValue<AwsHttps>(() => { 
           AwsHttps['credentialsPromise'] = undefined;
           return new AwsHttps();
}, MillisecondsInHour);
```

This is a hack, of course. Leave this issue open so that I can eventually manage it within the library.

**Comment by iursinoliveperson** [comment]
It caches it statically? Because I'm not keeping an instance around.

**Comment by kernwig** [comment]
Yes.

**Comment by iursinoliveperson** [comment]
It would be nice if the static caching could be disabled, but it would be good enough if the cache'd credential being expired would result in a retry.

At minimum since this project supports typescript, the means of clearing the cache needs to be available in typescript code (not a private field).

Thanks for the quick response though I really appreciate it.

**Comment by kernwig** [comment]
Continued as issue #39 .
