### ISSUE TITLE
Is it possible to use aws-https using a different credential pair than the default?

### ISSUE THREAD

**Issue by iursinoliveperson** [onicagroup/sailplane#39]
Our requirements changed from being able to use ECS task assumed roles to authenticate to requiring that our services pull an iam role's credentials and use those. (Strange but has something to do with our security model or something).

Is there any way to override the access key ID and access key secret with a random one (for example that I've pulled out of secrets manager using my assumed-role)?

**Comment by kernwig** [comment]
Hello @iursinoliveperson . Did you see PR #33?

You can set the credentials via AWS.Config.credentials (see [here](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/global-config-object.html) and [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html)), then use the new option in PR #33 .

Another option would be for `AwsHttps` to accept an `AWS.Config`  object in the constructor; which you can create as also described [here](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/global-config-object.html).

Thoughts?

**Comment by iursinoliveperson** [comment]
Yeah accepting an AWS.Config seems like the way to go since we need to use the retrieved iam user credentials only for our HTTP and continue to use the assumed-role for the secrets-manager sdk.

**Comment by iursinoliveperson** [comment]
Now that I think about it, my hack to work around the issue identified in #33 will work to inject my credentials for now.

**Comment by iursinoliveperson** [comment]
Ah not quite, because the credentials promise doesn't actually return a credential used by the client, instead we get it from the global one.

**Comment by kernwig** [comment]
@iursinoliveperson , please try out PR #44. The unit tests exercise it, but not in a real AWS account. The easy way to test it is to just pull a copy of this modified `aws-https/lib/aws-https.ts` into your project. Since I can't make you a reviewer, please comment with your results.
