### ISSUE TITLE
How to mock Injector.registerFactory

### ISSUE THREAD

**Issue by Benzer1406** [onicagroup/sailplane#63]
Hi,

I'm using sailplane `Injector` to to register a factory like this: 
`Injector.registerFactory("AuthenticationService", () => {
    return new AuthenticationService();
});`

Now, I came to the part of writing tests with `jest`. But I always get the error `Cannot read property \'changePassword\' of undefined'`. The AWS Lambda function has a line: ` const response = await authenticationService.changePassword(
            oldPassword, newPassword
        );`

When running the AWS Lambda function it works perfectly, but when running tests it is undefined. 

In the documentation I can only find one sentence: `It does require that unit test mocks be registered with the Injector rather than passed into the constructor.` But I don't understand what is meant with that and how an example would look like.

Thanks for ideas and help!

**Comment by kernwig** [comment]
Hmm. Interesting about that in the docs, since that is absolutely not a desired strategy.

It's implying that you can call `Injector.registerFactory"AuthenticationService", () => { return new MockAuthenticationService(); });` in your test to re-register with the mock. This doesn't usually work though, because you can't reregister. (I actually found that I do have a test doing this - not sure why it works!)

Instead, the whole reason we inject dependencies into a constructor is so that we can just use the constructor to pass in mocks and fakes. Doing this with jest and Typescript took me quite a bit of digging to figure out, so I'll share an example here with snippets of real code:

user.repository.ts:
```
import {Injector} from '@sailplane/injector';
import {DynamoDbService} from "../services/dynamodb.service";

export class UserRepository {
  static readonly $inject = [DynamoDbService]
  constructor(private ddb: DynamoDbService) {
  }

  get(userId: CognitoId): Promise<UserItem | undefined> {
    return this.ddb.get({
      Key: {
        _pk0: "User",
        _sk0: userId
      }
    });
  }
}

Injector.register(UserRepository);
```

user.repository.spec.ts:
```
import {UserRepository} from "./user.repository";
import {DynamoDbService} from "../services/dynamodb.service";

jest.mock("../services/dynamodb.service");
const MockedDynamoDbService = DynamoDbService as jest.Mock<DynamoDbService>;

describe('UserRepository', () => {
  beforeEach(() => {
    MockedDynamoDbService.mockClear();
  });

  describe('#get', () => {
    test('when getting a user', async () => {
      // GIVEN
      const ddb = new MockedDynamoDbService() as jest.Mocked<DynamoDbService>;
      ddb.get.mockResolvedValue(testUser as UserItem);
      const uut = new UserRepository(ddb);

      // WHEN
      const response = await uut.get(testUser.userId);

      // THEN
      expect(response).toEqual(testUser);
    });
  });
});
```

**Comment by Benzer1406** [comment]
@kernwig  Wow, thank you! Seems to work! Great help! Thank you!

**Comment by Benzer1406** [comment]
@kernwig  I picked up the tests again. The mock seems to be set up correctly, but something very weird happens:

In the Lambda function I run a console log and it shows: 
<img width="1029" alt="Captura de Tela 2020-12-30 às 22 27 45" src="https://user-images.githubusercontent.com/33852084/103392969-4b3ea280-4aee-11eb-9e84-ab39d25f978e.png">
The `authenticationService` is defined with all mock functions.

But then in the next line it turns to undefined:
<img width="666" alt="Captura de Tela 2020-12-30 às 22 28 55" src="https://user-images.githubusercontent.com/33852084/103392989-6dd0bb80-4aee-11eb-812a-52ce3601ec72.png">


Does that have something to do with how it is mocked? Any idea why the `authenticationService` suddenly turns to `undefined`?

**Comment by kernwig** [comment]
I'm not sure why the IDE is showing you different things between the two screen shots, but noticed that it isn't the value that has change, but rather _what_ it is showing. The first screenshot is showing you the definition of the `AuthenticationService` class. (Notice the capital 'A'.) The second is showing you a value. Is it the value of `authenticationService`, `changePassword` or the return value? (Did you mock a return value?)

Perhaps this line of thought will lead you to your solution.

**Comment by Benzer1406** [comment]
@kernwig  Thanks for your thoughts. Indeed it had something to do with it. According to the Jest documentation, an *auto* mocked module always returns `undefined` [("_It replaces the ES6 class with a mock constructor, and replaces all of its methods with mock functions that always return undefined._")](https://jestjs.io/docs/en/es6-class-mocks#automatic-mock).

So I changed my mock to this:

```
import AuthenticationService from "../../../controllers/auth.service";
jest.mock("../../../controllers/auth.service");

...
test(""), async ()=>{
AuthenticationService.mockImplementation(() => {
            return {
                changePassword: jest.fn(() => ({
                    statusCode: 200,
                    response: {
                        message: "Password successfully changed"
                    }
                }))
            };
        });
}
```

With that, together with the [lambda tester](https://www.npmjs.com/package/lambda-tester) I can test the (mocked) response object.


There is though one last issue. I had to comment the line that injects the class and construct it the "normal" way:

```
 // let authenticationService = Injector.getByName("AuthenticationService");
        const authenticationService = new AuthenticationService();
```

If I use ```let authenticationService = Injector.getByName("AuthenticationService");``` the ```authenticationService``` stays `undefined` in the test.

I think that was the original question I had and while implementing the solution I forgot that I changed the 2 lines. Any idea?

**Comment by kernwig** [comment]
Why are you using `Injector#getByName` instead of `Injector#get`? `getByName` is intended for constants and should be registered with `registerFactory` or `registerConstant`.

Sometimes mixing `Injector#register` and `getByName` will work, but not always due to the likes of webpack and other tools that will change your class names. If if the name matches, using the class name as a string breaks type safety and might be missed in a refactor.

**Comment by Benzer1406** [comment]
I use `registerFactory`: 
```
import { AuthenticationRepo } from "./authentication.repo";
Injector.registerFactory("AuthenticationRepo", () => new AuthenticationRepo());
```

I tried using `Injector.register("AuthenticationRepo);` but I get an error saying that the class is `undefined`. I use `Injector.getByName...` in my lambda functions and it works fine, but in the tests it is undefined.

**Comment by kernwig** [comment]
Are you pulling this in through your own shared library? So a dependency tree like:

```
  myapp-lambda
      myapp-shared
         @sailplane/injector
```

That's known to cause these problems. List @sailplane/injector as a peerDependency in myapp-shared, and then directly as a dependency in myapp-lambda. 

@sdechgan did I get this right; this was your scenario?

**Comment by Benzer1406** [comment]
Oh ok, that might be the issue then. My project structure is:
```
myapp-lambda
     services
           authentication
```

In the myapp-lambda I have a `package.json` that contains: 
```
"dependencies": {
        "@sailplane/injector": "^1.0.1",
        "@sailplane/lambda-utils": "^2.0.0",
        "@sailplane/logger": "^2.0.0",
...
```

In the authentication I have a `package.json` with:
```
  "dependencies": {
        "@sailplane/injector": "^1.0.1",
        "@sailplane/lambda-utils": "^3.0.0",
        "@sailplane/logger": "^2.0.1",
```

I had to install it on both levels otherwise the code didn't run. But on which level should I move the dependencies from `dependencies` to `peerDependencies`?

**Comment by kernwig** [comment]
Sorry about the delay getting back to you.

All libraries can declare @sailplane/injector (and possibly others) as peerDependencies and as devDependencies (for unit testing). The final application project that you actually build and deploy then pulls in the dependency.

A devDependency is used when you want the library in for running your coding (intellisense) and build (unit test) pipeline, but not to export it out as a specific dependency to other applications that use your library. It'll have something along the lines of:

```
"dependencies": {
        "@sailplane/injector": "^1.0.1",
        "@sailplane/lambda-utils": "^2.0.0",
        "@sailplane/logger": "^2.0.0"
}
"peerDependencies": {
        "@sailplane/injector": "1.x.x",
        "@sailplane/lambda-utils": "2.x.x",
        "@sailplane/logger": "2.x.x"
}
```

So here you're specifying a particular version for dev, but then telling any application using your library "Hey, you need to install some compatible version of these things - the exact version is up to you."

You continue this up multiple levels of libraries. (I've never done that, but sure.) So then the app has "dependencies" on your shared library, and all the peerDependencies. This ensures that only one copy of each library is installed.

Not doing this results in multiple copies of libraries - possibly of different versions. This works (but is bloat) on stateless libraries like lambda-utils, but not for something with singleton state like injector.
