### ISSUE TITLE
[logger] Setting globalLogLevel to 'NONE' with environment variable is broken

### ISSUE THREAD

**Issue by nwayve** [onicagroup/sailplane#64]
If you set the `LOG_LEVEL` environment variable to `'NONE'`, it gets set to the default log level of `'DEBUG'`.
This is because `LogLevelsMap[process.env.LOG_LEVEL || 'DEBUG']` resolves to the enum value of `0`, falsy, and so the `|| LogLevels.DEBUG` is chosen instead.

**Comment by kernwig** [comment]
Fixed
